{{- if not .Values.opsManager.secretRef }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-credential
  namespace: {{ .Release.Namespace }}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
  labels:
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    "app.kubernetes.io/managed-by": {{ .Release.Service }}

type: Opaque
data:
    user: {{ .Values.opsManager.APIKey | b64enc }}
    publicApiKey: {{ .Values.opsManager.APISecret | b64enc }}
{{- end }}
