---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-appdb
  namespace: {{ .Release.Namespace }}
  labels:
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
{{- if .Values.registry.imagePullSecrets}}
imagePullSecrets:
  - name: {{ .Values.registry.imagePullSecrets }}
{{- end }}


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-ops-manager
  namespace: {{ .Release.Namespace }}
  labels:
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
{{- if .Values.registry.imagePullSecrets }}
imagePullSecrets:
  - name: {{ .Values.registry.imagePullSecrets }}
{{- end }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  namespace: {{ .Release.Namespace }}
  labels:
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  namespace: {{ .Release.Namespace }}
  labels:
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-enterprise-appdb
subjects:
  - kind: ServiceAccount
    name: mongodb-enterprise-appdb
    namespace: {{ .Release.Namespace }}
