---
{{- if .Values.atlas.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
{{- if .Values.atlas.connectionSecretName }}
  name: {{ .Values.atlas.connectionSecretName}}
{{- else }}
  name: {{ include "atlas-cluster.fullname" . }}-secret
{{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlas-cluster.labels" . | nindent 4 }}
  annotations:
    'helm.sh/hook': post-delete,pre-install,pre-upgrade
data:
    orgId: {{ .Values.atlas.orgId| b64enc }}
    publicApiKey: {{ .Values.atlas.publicApiKey| b64enc }}
    privateApiKey: {{ .Values.atlas.privateApiKey| b64enc }}
{{- end }}
