{{- if .Values.project.create }}
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: {{ include "atlas-cluster.projectfullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlas-cluster.labels" . | nindent 4 }}
  {{- if .Values.project.annotations }}
  annotations:
{{ toYaml .Values.project.annotations | indent 4 }}
  {{- end }}
spec:
  name: {{ .Values.project.atlasProjectName }}
{{- if not .Values.mongodbAtlasOperator.clusterWide }}
  connectionSecretRef:
{{- if .Values.atlas.connectionSecretName }}
    name: {{ .Values.atlas.connectionSecretName}}
{{- else if and (not .Values.atlas.create) .Values.atlas.existingSecretName  }}
    name: {{ .Values.atlas.existingSecretName }}
{{- else }}
    name: {{ include "atlas-cluster.fullname" . }}-secret
{{- end }}
{{- end }}
  projectIpAccessList:
  {{- with .Values.project.projectIpAccessList }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
