{{- range .Values.clusters }}
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasCluster
metadata:
  name: {{ .name }}
  labels:
    {{- include "atlas-cluster.labels" $ | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
  {{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
  {{- end }}
spec:
  projectRef:
    name: {{ include "atlas-cluster.projectfullname" $ }}
  clusterSpec:
    name: {{ .name }}
    providerSettings:
  {{- with .providerSettings -}}
    {{- $provider := .providerName -}}
    {{- range $key, $val := . }}
    {{ if or (ne $key "backingProviderName") (and (eq $key "backingProviderName") (eq $provider "TENANT" )) }}
      {{- $key | indent 2 }}: {{ $val }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if .autoScaling }}
    autoScaling:
  {{- with .autoScaling }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .autoIndexingEnabled }}
      autoIndexingEnabled: false
  {{- end }}
  {{- if .biConnector }}
    biConnector:
      enabled: {{ .biConnector.enabled }}
      readPreference: {{ .biConnector.readPreference }}
  {{- end }}
  {{- if .clusterType }}
    clusterType: {{ .clusterType }}
  {{- end }}
  {{- if .diskSizeGB }}
    diskSizeGB: {{ .diskSizeGB }}
  {{- end }}
  {{- if .encryptionAtRestProvider }}
    encryptionAtRestProvider: {{ .encryptionAtRestProvider }}
  {{- end }}
  {{- if .labels }}
    labels:
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if .mongoDBMajorVersion }}
    mongoDBMajorVersion: {{ .mongoDBMajorVersion }}
  {{- end }}
  {{- if .numShards }}
    numShards: {{ .numShards }}
  {{- end }}
  {{- if .paused }}
    paused: {{ .paused }}
  {{- end }}
  {{- if .pitEnabled }}
    pitEnabled: {{ .pitEnabled }}
  {{- end }}
  {{- if .providerBackupEnabled }}
    providerBackupEnabled: {{ .providerBackupEnabled }}
  {{- end }}
  {{- if .replicationSpecs }}
    replicationSpecs:
    {{- with .replicationSpecs }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}

{{- if $.Values.postInstallHook.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name | quote }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ .name | quote }}
      labels:
        app.kubernetes.io/managed-by: {{ .name | quote }}
        app.kubernetes.io/instance: {{ .name | quote }}
    spec:
      serviceAccountName: mongodb-atlas-operator
      restartPolicy: Never
      containers:
        - name: post-install-job
          imagePullPolicy: Always
          image: "{{ $.Values.postInstallHook.registry }}/{{ $.Values.postInstallHook.image }}:{{ $.Values.postInstallHook.version }}"
          env:
            - name: "CLUSTER_NAME"
              value: "{{ .name }}"
            - name: "NAMESPACE"
              value: "{{ $.Release.Namespace }}"
{{- end }}
{{- end }}
