apiVersion: v2
name: mongodb-enterprise-database
description: MongoDB Kubernetes Enterprise Operator- MongoDB DataBase charts
version: 0.2.2
kubeVersion: '>=1.15-0'
keywords:
- mongodb
- database
- nosql
home: https://github.com/mongodb/mongodb-enterprise-kubernetes
icon: https://camo.githubusercontent.com/d473c25e361fb2206f06bdcf24028e8d52bc30d1/68747470733a2f2f6d6f6e676f64622d6b756265726e657465732d6f70657261746f722e73332e616d617a6f6e6177732e636f6d2f696d672f4c6561662d466f7265737425343032782e706e67
maintainers:
- name: theburi
  email: belika@hotmail.com
dependencies:
  - name: mongodb-enterprise-operator
    version: "0.3.0"
    repository: "https://mongodb.github.io/helm-charts"
    condition: mongodb-enterprise-operator.enabled
