## MongoDB Enterprise Database

# Set this to true if your cluster is managing SecurityContext for you.
# If running OpenShift (Cloud, Minishift, etc.), set this to true.
managedSecurityContext: false

# Section to describe components that needs to be installed
mongodb-enterprise-operator:
  enabled: true
  watchOpsManager: false
  watchDatabase: true

# Optional configuration.
deployValidationWebhooks: true

name: mdbreplset
type: ReplicaSet
members: 3
opsManager:
  # Ops Manager connection could be configured  with Values and This HELM chart will create
  # nesessary Secret and Config Map.
  URL:
  orgid:
  APIKey:
  APISecret:
  # Alternatevly an existing secret and config map could be provided directly
  configMap: opsmanager-configmap
  secretRef: opsmanager-org-access-key

security:
  authentication:
    modes: ["SCRAM"]  # Valid authentication modes are "SCRAM", "LDAP" and "X509"
  tls:
    enabled: false
    caRef: mdbreplset-ca
    # Note: Operator would expect Pem secret to have name: <metadata.name>-cert

resources:
  limits:
    cpu: 2
    memory: 1.5G
  requests:
    cpu: 1
    memory: 1G
tolerations: []

clusterName: cluster.local

registry:
  imagePullSecrets:
  # TODO: specify for each image and move there?
  pullPolicy: Always
  # Specify if images are pulled from private registry

users:
  - username: admin-user
    db: admin
    password: "%SomeLong%password$foradmin"
    roles:
      - db: admin
        name: clusterAdmin
      - db: admin
        name: userAdminAnyDatabase
      - db: admin
        name: readWrite
      - db: admin
        name: userAdminAnyDatabase
  - username: app-user
    db: admin
    password: "%SomeLong%password$"
    roles:
      - db: admin
        name: readWrite
