---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    email: support@mongodb.com
  labels:
    owner: mongodb
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ int .Values.operator.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.operator.name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: {{ .Values.operator.name }}
    spec:
      {{- with .Values.operator.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - command:
            - /usr/local/bin/entrypoint
          env:
            {{- with .Values.operator.extraEnvs }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
            - name: WATCH_NAMESPACE
              {{- if .Values.operator.watchNamespace}}
              value: "{{ .Values.operator.watchNamespace }}"
              {{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
              {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ .Values.operator.name }}
            - name: AGENT_IMAGE
              value: "{{ .Values.registry.agent }}/{{ .Values.agent.name }}:{{ .Values.agent.version }}"
            - name: VERSION_UPGRADE_HOOK_IMAGE
              value: "{{ .Values.registry.versionUpgradeHook }}/{{ .Values.versionUpgradeHook.name }}:{{ .Values.versionUpgradeHook.version }}"
            - name: READINESS_PROBE_IMAGE
              value: "{{ .Values.registry.readinessProbe }}/{{ .Values.readinessProbe.name }}:{{ .Values.readinessProbe.version }}"
            - name: MONGODB_IMAGE
              value: {{ .Values.mongodb.name }}
            - name: MONGODB_REPO_URL
              value: {{ .Values.mongodb.repo }}
          image: {{ .Values.registry.operator }}/{{ .Values.operator.operatorImageName }}:{{ .Values.operator.version }}
          imagePullPolicy: {{ .Values.registry.pullPolicy}}
          name: {{ .Values.operator.deploymentName }}
          {{- with .Values.operator.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.operator.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.operator.schedulerName }}
      schedulerName: {{ . | quote }}
      {{- end }}
      {{- with .Values.operator.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.operator.name }}
      {{- with .Values.operator.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
