# Please provide Atlas API credentials and Organization
atlas:
  create: true
  existingSecretName: ""
  orgId: "<Atlas Organization ID>"
  publicApiKey: "<Atlas_api_public_key>"
  privateApiKey: "<Atlas_api_private_key>"

  connectionSecretName: ""

project:
  create: true
  name: my-project
  atlasProjectName: "Test Project"
  annotations:
    {}
    # mongodb.com/atlas-resource-policy: keep
  # fullnameOverride: ""

  projectIpAccessList:
    - ipAddress: "0.0.0.0/1"
      comment: "REMOVE ME"

clusters:
  - name: cluster-name
    annotations:
      {}
      # mongodb.com/atlas-resource-policy: keep
    providerSettings:
      instanceSizeName: M2
      providerName: TENANT
      backingProviderName: AWS
      regionName: US_EAST_1

# Optional section. for more information visit
# https://docs.atlas.mongodb.com/reference/api/clusters-create-one/
# #
#   autoScaling:
#     autoIndexingEnabled: false
#     compute:
#       enabled: false
#       maxInstanceSize: 'M40'
#       minInstanceSize: 'M10'
#       scaleDownEnabled: false
#     diskGBEnabled: false
#   biConnector:
#     enabled: false
#     readPreference: 'primary'
#   clusterType: 'REPLICASET'
#   diskSizeGB: '50'
#   encryptionAtRestProvider: 'AWS'
#   labels:
#   mongoDBMajorVersion: '4.4'
#   numShards: 2
#   paused: false
#   pitEnabled: false
#   providerBackupEnabled: false
#   replicationSpecs:
users:
  - username: admin-user
    databaseName: admin
    password:
    roles:
      - databaseName: admin
        roleName: atlasAdmin
    # deleteAfterDate:
    # labels:
    # scopes:
