mongodbAtlasOperator:
  enabled: true

postInstallHook:
  version: 1.0.1
  registry: quay.io/mongodb
  image: atlas-operator-post-install-hook
  # enabled "true" will create a post install job which waits for the created
  # resources to reach the ready state.
  enabled: false

# Please provide Atlas API credentials and Organization
atlas:
  secret:
    # project uses Global Key (highest priority)
    global: false
    # secret already exist in the same namespace
    existing: ""

    orgId: "<Atlas Organization ID>"
    publicApiKey: "<Atlas_api_public_key>"
    privateApiKey: "<Atlas_api_private_key>"
    # use custom secret name during new secret creation
    setCustomName: ""


project:
  create: true
  name: my-project
  atlasProjectName: "Test Project"
  annotations: {}
    # mongodb.com/atlas-resource-policy: keep
  # fullnameOverride: ""

  projectIpAccessList:
    - ipAddress: "0.0.0.0/1"
      comment: "REMOVE ME"

# include either clusterSpec or advancedClusterSpec
# see https://docs.atlas.mongodb.com/reference/api/cluster-advanced/create-one-cluster-advanced/ for
# options for creating advanced clusters.
clusters:
  - clusterSpec:
      name: cluster-name
      annotations: {}
        # mongodb.com/atlas-resource-policy: keep
      providerSettings:
        instanceSizeName: M2
        providerName: TENANT
        backingProviderName: AWS
        regionName: US_EAST_1

# Additional clusterSpec values
# Optional section. for more information visit
# https://docs.atlas.mongodb.com/reference/api/clusters-create-one/
# #
#   autoScaling:
#     autoIndexingEnabled: false
#     compute:
#       enabled: false
#       maxInstanceSize: 'M40'
#       minInstanceSize: 'M10'
#       scaleDownEnabled: false
#     diskGBEnabled: false
#   biConnector:
#     enabled: false
#     readPreference: 'primary'
#   clusterType: 'REPLICASET'
#   diskSizeGB: '50'
#   encryptionAtRestProvider: 'AWS'
#   labels:
#   mongoDBMajorVersion: '4.4'
#   numShards: 2
#   paused: false
#   pitEnabled: false
#   providerBackupEnabled: false
#   replicationSpecs:

# Configure a Serverless Instance
# https://www.mongodb.com/docs/atlas/reference/api/serverless/create-one-serverless-instance/

#  - serverlessSpec:
#      name: serverless-instance
#      providerSettings:
#        providerName: SERVERLESS
#        backingProviderName: AWS
#        regionName: US_EAST_1

# Configure an Advanced Cluster
# https://www.mongodb.com/docs/atlas/reference/api/cluster-advanced/create-one-cluster-advanced/

#  - advancedClusterSpec:
#      clusterType: REPLICASET
#      name: advanced-cluster
#      replicationSpecs:
#        - regionConfigs:
#            - electableSpecs:
#                instanceSize: M5
#              providerName: TENANT
#              backingProviderName: AWS
#              regionName: US_EAST_1

users:
  - username: admin-user
    databaseName: admin
    password:
    roles:
      - databaseName: admin
        roleName: atlasAdmin
    # deleteAfterDate:
    # labels:
    # scopes:
