mongodb-atlas-operator:
  enabled: true

# Please provide Atlas API credentials and Organization
atlas:
  orgId: "<Atlas Organization ID>"
  publicApiKey: "<Atlas_api_public_key>"
  privateApiKey: "<Atlas_api_private_key>"

  connectionSecretName: ""

project:
  name: "kube-project-1"
  atlasProjectName: "kube-project-1"
  # fullnameOverride: ""

  projectIpAccessList:
    - ipAddress: "192.0.2.15"
      comment: "IP address for Application Server A"
    - ipAddress: "203.0.113.0/24"
      comment: "CIDR block for Application Server B - D"

mongodb:
  providerSettings:
    instanceSizeName: M2
    providerName: TENANT
    backingProviderName: AWS
    regionName: US_EAST_1

# Optional section. for more information visit
# https://docs.atlas.mongodb.com/reference/api/clusters-create-one/
# #
#   autoScaling:
#     autoIndexingEnabled: false
#     compute:
#       enabled: false
#       maxInstanceSize: 'M40'
#       minInstanceSize: 'M10'
#       scaleDownEnabled: false
#     diskGBEnabled: false
#   biConnector:
#     enabled: false
#     readPreference: 'primary'
#   clusterType: 'REPLICASET'
#   diskSizeGB: '50'
#   encryptionAtRestProvider: 'AWS'
#   labels:
#   mongoDBMajorVersion: '4.4'
#   numShards: 2
#   paused: false
#   pitEnabled: false
#   providerBackupEnabled: false
#   replicationSpecs:
users:
  - username: admin-user
    databaseName: admin
    password: "%SomeLong%password$foradmin"
    roles:
      - databaseName: admin
        roleName: atlasAdmin
    # deleteAfterDate:
    # labels:
    # scopes:
